import { test, expect } from '@playwright/test'

test('diary ranges become a dated calendar and replacement work stays separate from Done', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-04T12:00:00Z') })
  await page.clock.setFixedTime(new Date('2026-10-04T12:00:00Z'))
  await page.goto('/auth'); await page.getByRole('button', { name: 'Continue on this device' }).click()
  await page.goto('/plan?date=2026-10-02')
  await page.getByLabel(/One task per line/).fill('09:00–10:30 Study physics\n14:00–15:00 Project work')
  await page.getByRole('button', { name: 'Prepare editable draft' }).click()
  await expect(page.getByLabel('Estimate (min)').first()).toHaveValue('90')
  await expect(page.getByLabel('Google Calendar reminder (minutes before)').first()).toHaveValue('10')
  await page.getByRole('button', { name: 'Approve day', exact: true }).click()
  await page.getByRole('link', { name: 'Open day calendar' }).click()
  await expect(page.getByRole('heading', { name: 'Friday, October 2' })).toBeVisible()
  await page.getByRole('button', { name: 'What happened?' }).first().click()
  await page.getByRole('button', { name: 'Did something else', exact: true }).click()
  await page.getByLabel('What did you do instead?').fill('Helped family with errands')
  await page.getByLabel('How certain is the timing?').selectOption('same')
  await page.getByRole('button', { name: 'Save check-in' }).click()
  await expect(page.getByText('Instead: Helped family with errands')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Instead: Helped family with errands')).toBeVisible()
  await page.getByRole('button', { name: 'Month', exact: true }).click()
  await page.getByRole('button', { name: 'View day 2026-10-02', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Friday, October 2' })).toBeVisible()
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem('lifeos:v2:guest-local:snapshot')).state)
  expect(state.planning.checkins[0].outcome).toBe('other')
  expect(state.timeflow.entries[0].blockId).toBeNull()
  expect(state.timeflow.entries[0].description).toBe('Helped family with errands')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: 'docs/screenshots/calendar-day-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'docs/screenshots/calendar-day-desktop.png', fullPage: true })
  await page.goto('/insights')
  await expect(page.getByRole('heading', { name: 'Intention & recorded time' })).toBeVisible()
  await page.screenshot({ path: 'docs/screenshots/planning-insights.png', fullPage: true })
})

test('old Drive records preview and merge into the signed-in owner without duplicates', async ({ page, context }) => {
  const owner = 'drive-import-browser-owner'
  await context.addInitScript(() => Object.defineProperty(navigator, 'onLine', { configurable: true, get: () => false }))
  await page.route('**/api/session', route => route.fulfill({ json: { user: { id: owner, name: 'Fixture' }, csrf: 'fixture', capabilities: { auth: true }, integration: { state: 'connected', scopes: 'https://www.googleapis.com/auth/drive.readonly' } } }))
  await page.route('**/api/shares', route => route.fulfill({ json: { shares: [] } }))
  await page.route('**/api/drive/folders?*', route => route.fulfill({ json: { folders: [{ id: 'folder-123', name: 'LifeOS-Data' }] } }))
  await page.route('**/api/drive/preview?*', route => route.fulfill({ json: { files: [{ id: 'finance-123', name: 'finance.json', size: 120, modifiedTime: '2026-09-01' }] } }))
  await page.route('**/api/drive/read', route => route.fulfill({ json: { ownerId: owner, folderId: 'folder-123', modules: { finance: { expenses: [{ id: 'legacy-payment', date: '2026-10-02', amount: 250, currency: 'INR', category: 'Food', description: 'Old Drive lunch' }] } }, originals: [{ id: 'finance-123', name: 'finance.json' }] } }))
  await page.goto('/me')
  await page.getByRole('button', { name: 'Find my old data' }).click()
  await expect(page.getByText('finance.json', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Preview selected records' }).click()
  await expect(page.getByText(/1 array items to add/)).toBeVisible()
  await page.getByRole('button', { name: 'Merge into my LifeOS account' }).click()
  await expect(page.getByRole('status')).toContainText('1 items added')
  await page.getByRole('button', { name: 'Preview selected records' }).click()
  await page.getByRole('button', { name: 'Merge into my LifeOS account' }).click()
  await expect(page.getByRole('status')).toContainText('0 items added')
  const snapshot = await page.evaluate(owner => JSON.parse(localStorage.getItem(`lifeos:v2:${owner}:snapshot`)), owner)
  expect(snapshot.state.finance.expenses).toHaveLength(1)
  expect(snapshot.pendingModuleChanges.length).toBeGreaterThan(0)
  expect(await page.evaluate(owner => Object.keys(localStorage).filter(k => k.startsWith(`lifeos:v2:${owner}:drive-import:`)).length, owner)).toBe(2)
  await page.goto('/finance')
  await page.getByLabel('Finance month', { exact: true }).fill('2026-10')
  await expect(page.getByText('Old Drive lunch', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Spending through the month' })).toBeVisible()
  await page.screenshot({ path: 'docs/screenshots/finance-imported-mobile.png', fullPage: true })
})
