import { test, expect } from '@playwright/test'

const snapshot = page => page.evaluate(() => JSON.parse(localStorage.getItem('lifeos:v2:guest-local:snapshot')).state)
async function localWorkspace(page) {
  await page.clock.install({ time: new Date('2026-10-03T06:30:00Z') })
  await page.clock.setFixedTime(new Date('2026-10-03T06:30:00Z'))
  await page.goto('/auth')
  await page.getByRole('button', { name: /Continue on this device/i }).click()
  await expect(page.locator('#main-content h1')).toBeVisible()
}

test('approve a date, reload, report Done with unknown timing without inventing activity', async ({ page }) => {
  await localWorkspace(page)
  await page.goto('/plan')
  await page.getByLabel('Planning date').fill('2026-10-03')
  await page.getByLabel(/One task per line/).fill('09:00 Thermodynamics 60 min must')
  await page.getByRole('button', { name: /Prepare editable draft/ }).click()
  await expect(page.getByLabel('Task 1', { exact: true })).toHaveValue('09:00 Thermodynamics 60 min must')
  await page.getByRole('button', { name: 'Approve day', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Approved 2026-10-03, revision 1')
  await page.reload()
  await expect(page.getByText('Revision 1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Approve day', exact: true }).click()
  expect((await snapshot(page)).planning.revisions).toHaveLength(1)
  await page.goto('/')
  await page.getByRole('button', { name: 'Check in', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('How certain is the timing?')).toHaveValue('unknown')
  await dialog.getByRole('button', { name: 'Save check-in', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await expect(page.getByText('1/1 original outcomes completed', { exact: false })).toBeVisible()
  const state = await snapshot(page)
  expect(state.planning.checkins[0].outcome).toBe('done')
  expect(state.planning.checkins[0].timing).toBe('unknown')
  expect(state.timeflow.entries).toHaveLength(0)
  await page.screenshot({ path: 'docs/screenshots/today-checkin-mobile.png', fullPage: true })
})

test('local timer recovers after reload, subtracts a pause, and saves confirmed intervals once', async ({ page }) => {
  await localWorkspace(page)
  await page.goto('/focus')
  await page.getByLabel('Or name an unplanned focus task').fill('Draft the project outline')
  await page.getByRole('button', { name: 'Use this task', exact: true }).click()
  await page.getByRole('button', { name: 'Start task', exact: true }).click()
  await page.clock.setFixedTime(new Date('2026-10-03T06:50:00Z'))
  await page.reload()
  await expect(page.getByRole('timer')).toHaveText('00:20:00')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.clock.setFixedTime(new Date('2026-10-03T07:00:00Z'))
  await expect(page.getByRole('timer')).toHaveText('00:20:00')
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.clock.setFixedTime(new Date('2026-10-03T07:10:00Z'))
  await page.getByRole('button', { name: 'Stop & check in', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('How certain is the timing?').selectOption('timer')
  await dialog.getByRole('button', { name: 'Save check-in', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  const state = await snapshot(page)
  expect(state.planning.timer).toBeNull()
  expect(state.timeflow.entries).toHaveLength(2)
  expect(state.timeflow.entries.reduce((sum, entry) => sum + entry.durationMinutes, 0)).toBe(30)
  expect(new Set(state.timeflow.entries.map(entry => entry.id)).size).toBe(2)
})

test('reviewed capture uses debit paise, persists offline, and rejects a reference duplicate', async ({ page, context }) => {
  await localWorkspace(page)
  await page.goto('/capture')
  await page.getByLabel('What are you capturing?').selectOption('money')
  await context.setOffline(true)
  await page.getByLabel('Text or intentional paste').fill('A/c XX1234 debited Rs.1,250.00 to BOOK SHOP on 2026-10-03. UPI ref 123456789012. Avl balance ₹8,000')
  await page.getByRole('button', { name: 'Save to inbox', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Amount (INR)')).toHaveValue('1250.00')
  await dialog.getByRole('button', { name: 'Close dialog' }).click()
  await context.setOffline(false)
  await page.reload()
  await page.getByRole('button', { name: 'Review', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Confirm transaction', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByLabel('What are you capturing?').selectOption('money')
  await page.getByLabel('Text or intentional paste').fill('A/c XX1234 debited Rs.1,250.00. UPI ref 123456789012. Avl balance ₹8,000')
  await page.getByRole('button', { name: 'Save to inbox', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm transaction', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('already exist in Money')
  const state = await snapshot(page)
  expect(state.finance.expenses).toHaveLength(1)
  expect(state.finance.expenses[0].amountMinor).toBe(125000)
  expect(state.captures.items.find(c => c.status === 'confirmed').text).toBe('')
  await page.screenshot({ path: 'docs/screenshots/capture-review-mobile.png', fullPage: true })
})

