import { test, expect } from '@playwright/test'

test('meditation countdown survives reload and never logs until explicit confirmation', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-03T06:30:00Z') })
  await page.clock.setFixedTime(new Date('2026-10-03T06:30:00Z'))
  await page.goto('/auth')
  await page.getByRole('button', { name: /Continue on this device/i }).click()
  await expect(page.locator('main h1')).toBeVisible()
  await page.goto('/meditations')
  await page.getByRole('button', { name: '1m', exact: true }).click()
  await page.getByRole('button', { name: 'Begin Meditation' }).click()
  await page.clock.setFixedTime(new Date('2026-10-03T06:31:00Z'))
  await page.reload()
  await expect(page.getByRole('status').filter({ hasText: 'Nothing is logged' })).toBeVisible()
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('lifeos:v2:guest-local:snapshot')).state)
  expect(before.meditations.sessions).toHaveLength(0)
  expect(before.timeflow.entries).toHaveLength(0)
  await page.getByRole('button', { name: 'Confirm meditation session' }).click()
  await page.reload()
  let state = await page.evaluate(() => JSON.parse(localStorage.getItem('lifeos:v2:guest-local:snapshot')).state)
  expect(state.meditations.sessions).toHaveLength(1)
  expect(state.meditations.sessions[0].minutes).toBe(1)
  expect(state.timeflow.entries).toHaveLength(1)
  expect(state.timeflow.entries[0].startAt).toBeUndefined()
  expect(state.meditations.activeTimer).toBeNull()

  await page.getByRole('button', { name: '1m', exact: true }).click()
  await page.getByRole('button', { name: 'Begin Meditation' }).click()
  await page.clock.setFixedTime(new Date('2026-10-03T06:31:30Z'))
  await page.getByRole('button', { name: 'Finish & review', exact: true }).click()
  await expect(page.getByLabel('Meditation minutes to confirm')).toHaveValue('0.50')
  await page.getByRole('button', { name: 'Confirm meditation session' }).click()
  state = await page.evaluate(() => JSON.parse(localStorage.getItem('lifeos:v2:guest-local:snapshot')).state)
  expect(state.meditations.sessions).toHaveLength(2)
  expect(state.timeflow.entries).toHaveLength(2)
  expect(state.meditations.sessions[0].minutes).toBe(0.5)
})
