import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.route('**/api/google-auth?action=config', route => route.fulfill({ json: { configured: false } }))
  await page.route('https://www.googleapis.com/**', route => route.fulfill({ status: 401, json: {} }))
  await page.addInitScript(() => {
    if (sessionStorage.getItem('test-initialized')) return
    localStorage.clear()
    localStorage.setItem('lifeos_google_session', JSON.stringify({ user: { id: 'test-user', name: 'Test User' }, tokenExpiresAt: 1 }))
    localStorage.setItem('lifeos_google_client_id', 'test-client')
    localStorage.setItem('lifeos-app-state-v1', JSON.stringify({ settings: { profile: { name: 'Test User', timezone: 'Asia/Kolkata' } }, timeflow: { entries: [], plans: [] }, finance: { expenses: [] } }))
    sessionStorage.setItem('test-initialized', 'yes')
  })
})
test('manual plan, changed activity, validation, persistence and mobile layout', async ({ page }) => {
  await page.goto('/timeflow')
  const date = page.locator('input[type="date"]').first()
  await date.fill('2026-01-05')
  await page.getByRole('button', { name: 'Plan my day', exact: true }).click()
  const modal = page.getByRole('dialog', { name: /Plan your day/ })
  await modal.getByLabel('Activity 1', { exact: true }).fill('Study maths')
  await modal.getByLabel('Start 1', { exact: true }).fill('09:00')
  await modal.getByLabel('End 1', { exact: true }).fill('10:00')
  await modal.getByLabel('Automatically sync to Google Calendar').uncheck()
  await modal.getByRole('button', { name: 'Save tentative plan' }).click()
  await expect(page.getByText('Actual: awaiting your confirmation')).toBeVisible()
  await page.getByRole('button', { name: 'What did you do?' }).click()
  const check = page.getByRole('dialog', { name: 'Plan check-in', exact: true })
  await check.getByLabel('Did you do the planned activity?').selectOption('changed')
  await check.getByLabel('What did you actually do?').fill('Rested')
  await check.getByRole('button', { name: 'Save actual & reflection' }).click()
  await expect(check.getByRole('alert')).toContainText('why the plan changed')
  await check.getByLabel('Why did the plan change? / reflection').fill('Needed a break')
  await check.getByRole('button', { name: 'Save actual & reflection' }).click()
  await expect(page.getByText('Actual: 09:00–10:00 · Rested (changed)')).toBeVisible()
  await expect(page.getByText('0% adherence (reviewed time)')).toBeVisible()
  await page.reload()
  await page.locator('input[type="date"]').first().fill('2026-01-05')
  await expect(page.getByText('Why: Needed a break')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('input[type="date"]').first().fill('2026-01-05')
  await expect(page.getByRole('button', { name: 'Edit plan', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/planner-mobile.png', fullPage: true })
})
test('typed AI plan and photo options are editable; overlapping AI output cannot be saved', async ({ page }) => {
  await page.route('**/generativelanguage.googleapis.com/**', route => route.fulfill({ json: { candidates: [{ content: { parts: [{ text: JSON.stringify({ slots: [{ name: 'Study', start: '09:00', end: '11:00', category: 'Study' }, { name: 'Gym', start: '10:00', end: '12:00', category: 'Exercise' }], assumptions: ['Suggested times'], questions: [] }) }] } }] } }))
  await page.goto('/timeflow')
  await page.evaluate(() => localStorage.setItem('lifeos_gemini_api_key', 'test-only-key'))
  await page.getByRole('button', { name: 'Plan my day', exact: true }).click()
  const modal = page.getByRole('dialog', { name: /Plan your day/ })
  await expect(modal.getByRole('button', { name: 'Take photo' })).toBeVisible()
  await expect(modal.getByRole('button', { name: 'Upload diary' })).toBeVisible()
  await modal.locator('input[type="file"]').first().setInputFiles({ name: 'diary.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jC1sAAAAASUVORK5CYII=', 'base64') })
  await expect(modal.getByAltText('Selected diary page')).toBeVisible()
  await modal.getByLabel('Tentative day plan').fill('Study and gym')
  await modal.getByRole('button', { name: 'Generate timeline' }).click()
  await expect(modal.getByLabel('Activity 1', { exact: true })).toHaveValue('Study')
  await modal.getByRole('button', { name: 'Save tentative plan' }).click()
  await expect(modal.getByRole('alert')).toContainText('overlaps')
  await modal.getByLabel('Start 2', { exact: true }).fill('11:00')
  await modal.getByLabel('Automatically sync to Google Calendar').uncheck()
  await modal.getByRole('button', { name: 'Save tentative plan' }).click()
  await expect(page.getByText('180m planned')).toBeVisible()
})

test('finance savings, subscriptions and comma-separated SMS imports work', async ({ page }) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/finance')
  await page.getByRole('button', { name: /Savings/ }).click()
  await expect(page.getByText('No savings goals created')).toBeVisible()
  await page.getByRole('button', { name: /Subscriptions & Debt/ }).click()
  await expect(page.getByRole('button', { name: /Subscriptions \(0\)/ })).toBeVisible()
  await page.getByRole('button', { name: /SMS/ }).click()
  const modal = page.getByRole('dialog', { name: /UPI SMS Auto-Import/ })
  await modal.locator('textarea').fill('HDFC: Paid Rs. 1,200.50 to Zomato on 05/10/2026')
  await modal.getByRole('button', { name: /Parse/ }).click()
  await expect(modal.locator('input[type="number"]')).toHaveValue('1200.5')
  expect(errors).toEqual([])
})

test('Calendar sync edits existing events and removes them when disabled', async ({ page }) => {
  const events = new Map()
  let inserts = 0, deletes = 0
  await page.route('https://www.googleapis.com/calendar/v3/**', async route => {
    const request = route.request(), id = new URL(request.url()).pathname.split('/').pop()
    const body = request.method() === 'DELETE' ? null : request.postDataJSON()
    if (request.method() === 'POST') {
      inserts++; events.set(body.id, body)
      return route.fulfill({ json: { id: body.id, htmlLink: 'https://calendar.google.com/test' } })
    }
    if (request.method() === 'DELETE') { deletes++; events.delete(id); return route.fulfill({ status: 204 }) }
    if (!events.has(id)) return route.fulfill({ status: 404, json: {} })
    events.set(id, body)
    return route.fulfill({ json: { id, htmlLink: 'https://calendar.google.com/test' } })
  })
  await page.goto('/timeflow')
  await page.evaluate(() => {
    const session = JSON.parse(localStorage.getItem('lifeos_google_session'))
    localStorage.setItem('lifeos_google_session', JSON.stringify({ ...session, accessToken: 'test-only', tokenExpiresAt: Date.now() + 3600000 }))
  })
  await page.getByRole('button', { name: 'Plan my day', exact: true }).click()
  let modal = page.getByRole('dialog', { name: /Plan your day/ })
  await modal.getByLabel('Activity 1', { exact: true }).fill('Calendar test')
  await modal.getByRole('button', { name: 'Save tentative plan' }).click()
  await expect(page.getByText(/Calendar up to date/)).toBeVisible()
  expect(inserts).toBe(1)
  await page.getByRole('button', { name: 'Edit plan', exact: true }).click()
  modal = page.getByRole('dialog', { name: /Plan your day/ })
  await modal.getByLabel('Activity 1', { exact: true }).fill('Updated calendar test')
  await modal.getByRole('button', { name: 'Save tentative plan' }).click()
  await expect.poll(() => [...events.values()][0]?.summary).toBe('Updated calendar test')
  expect(inserts).toBe(1)
  await page.getByRole('button', { name: 'Edit plan', exact: true }).click()
  modal = page.getByRole('dialog', { name: /Plan your day/ })
  await modal.getByLabel('Automatically sync to Google Calendar').uncheck()
  await modal.getByRole('button', { name: 'Save tentative plan' }).click()
  await expect.poll(() => deletes).toBe(1)
  expect(events.size).toBe(0)
})
