import { test, expect } from '@playwright/test'

test('waste survives plan/check-in and additional segments never overwrite earlier actuals', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/api/google-auth?action=config', route => route.fulfill({ json: { configured: false } }))
  await page.route('https://www.googleapis.com/**', route => route.fulfill({ status: 401, json: {} }))
  await page.addInitScript(() => {
    if (sessionStorage.getItem('accounting-test')) return
    localStorage.clear()
    localStorage.setItem('lifeos_google_session', JSON.stringify({ user: { id: 'test-user', name: 'Test' }, tokenExpiresAt: 1 }))
    localStorage.setItem('lifeos_google_client_id', 'test-client')
    localStorage.setItem('lifeos-app-state-v1', JSON.stringify({ settings: { profile: { name: 'Test', timezone: 'Asia/Kolkata' } }, timeflow: { entries: [], plans: [] } }))
    sessionStorage.setItem('accounting-test', 'yes')
  })
  await page.goto('/timeflow')
  await page.locator('input[type="date"]').first().fill('2026-01-05')
  await page.getByRole('button', { name: 'Plan my day', exact: true }).click()
  const plan = page.getByRole('dialog', { name: /Plan your day/ })
  await plan.getByLabel('Activity 1', { exact: true }).fill('Sleep')
  await plan.getByLabel('Category 1', { exact: true }).selectOption('Sleep')
  await plan.getByLabel('Waste 1', { exact: true }).check()
  await plan.getByLabel('Automatically sync to Google Calendar').uncheck()
  await plan.getByRole('button', { name: 'Save tentative plan' }).click()
  await page.getByRole('button', { name: 'Check in', exact: true }).click()
  const check = page.getByRole('dialog', { name: 'Plan check-in', exact: true })
  await expect(check.getByLabel('Count as waste (keep category)')).toBeChecked()
  await check.getByRole('combobox').first().selectOption('partial')
  await check.getByLabel('End time (HH:mm)').fill('09:30')
  await check.getByRole('button', { name: 'Save check-in', exact: true }).click()
  await expect(check).not.toBeVisible()
  await page.getByRole('button', { name: '+ Add log' }).click()
  await check.getByLabel('What did you actually do?').fill('Study')
  await check.getByLabel('Category', { exact: true }).selectOption('Study')
  await check.getByLabel('Start time').fill('09:15')
  await check.getByRole('button', { name: 'Save check-in', exact: true }).click()
  await expect(check.getByRole('alert')).toContainText('Overlaps')
  await check.getByLabel('Start time').fill('09:30')
  await check.getByRole('button', { name: 'Save check-in', exact: true }).click()
  await expect(check).not.toBeVisible()
  const entries = await page.evaluate(() => JSON.parse(localStorage.getItem('lifeos-module-state-v1:timeflow')).entries)
  expect(entries).toHaveLength(2)
  expect(new Set(entries.map(e => e.id)).size).toBe(2)
  expect(entries.find(e => e.category === 'Sleep')).toMatchObject({ start: '09:00', end: '09:30', isWaste: true })
  expect(entries.find(e => e.category === 'Study')).toMatchObject({ start: '09:30', end: '10:00', isWaste: false })
  await page.reload()
  await page.locator('input[type="date"]').first().fill('2026-01-05')
  await expect(page.getByText('50% adherence (reviewed time)')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('input[type="date"]').first().fill('2026-01-05')
  await expect(page.getByText('50% adherence (reviewed time)')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/timeflow-accounting-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})
