import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Wallet, BookOpen, Heart, NotebookPen, CheckSquare, Target, Clock, Settings, ArrowUpRight, Users, Library, Wind, Brain, Download, Cloud } from 'lucide-react'
import { useAppActions, useAppState } from '../context/appHooks'
import { useAuth } from '../context/appContextCore'
import { connectGoogle, disconnectGoogle } from '../services/authService'
import Button from '../components/ui/Button'
import Input from '../components/ui/Input'
import DriveImport from '../components/DriveImport'
const areas = [
  ['/finance', 'Money', 'Spending, budgets and recurring bills', Wallet], ['/study', 'Study', 'Subjects, sessions and learning goals', BookOpen],
  ['/health', 'Health & sleep', 'Sleep, movement and measurements', Heart], ['/habits', 'Routines', 'Small actions on your own schedule', CheckSquare],
  ['/journal', 'Journal', 'Reflections and writing', NotebookPen], ['/brain', 'Notes', 'Ideas, references and knowledge', Brain],
  ['/goals', 'Goals', 'Outcomes, milestones and next actions', Target], ['/timeflow', 'Actual timeline', 'Record, review and correct your time', Clock],
]
const optional = [['/readings', 'Books', 'Reading progress and sessions', Library], ['/crm', 'People', 'Private notes and chosen reminders', Users], ['/meditations', 'Meditation', 'Quiet practice and session notes', Wind]]
export default function Me() {
  const state = useAppState(), { updateModule, synchronize } = useAppActions()
  const { user, logout, capabilities = {}, integration = {}, refreshSession } = useAuth()
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [query, setQuery] = useState('')
  const optionalEnabled = state.settings?.preferences?.optionalModules || []
  async function run(action) { setBusy(true); setError(''); try { await action() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  function toggleModule(path) { updateModule('settings', s => ({ ...s, preferences: { ...s.preferences, optionalModules: optionalEnabled.includes(path) ? optionalEnabled.filter(p => p !== path) : [...optionalEnabled, path] } })) }
  const areaCard = ([to, title, description, Icon]) => <Link className="area-link" to={to} key={to}><Icon size={22}/><div><h3>{title}</h3><p>{description}</p></div></Link>
  const matches = area => `${area[1]} ${area[2]}`.toLowerCase().includes(query.toLowerCase())
  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">YOUR LIFE, YOUR SETTINGS</p><h1>Your space.</h1><p>{user?.isGuest ? 'A private workspace on this device.' : user?.name || 'Your areas, integrations and controls.'}</p></div><Link className="button button-secondary" to="/settings"><Settings size={17}/>Preferences</Link></header>
    <section className="section-card"><div className="section-heading"><h2>Your areas</h2><Link to="/capture">Capture something <ArrowUpRight size={15}/></Link></div><Input label="Find an area" placeholder="Search Money, Study, Notes…" value={query} onChange={e => setQuery(e.target.value)}/><div className="area-grid" style={{ marginTop: '1rem' }}>{areas.filter(matches).map(areaCard)}{optional.filter(([path]) => optionalEnabled.includes(path)).filter(matches).map(areaCard)}</div><div className="form-grid" style={{ marginTop: '1.5rem' }}><div className="field"><label htmlFor="quick-area">Quick area shortcut</label><select id="quick-area" value={state.settings?.preferences?.quickArea || '/finance'} onChange={e => updateModule('settings', s => ({ ...s, preferences: { ...s.preferences, quickArea: e.target.value } }))}>{areas.map(([path, name]) => <option key={path} value={path}>{name}</option>)}</select></div><div><p className="caption">Money stays one tap away from desktop navigation and today's spending card. Choose another area for your personal shortcut.</p></div></div></section>
    <section className="section-card"><div className="section-heading"><h2>Connections & data</h2><Cloud size={20}/></div><div className="page-stack"><div className="notice"><strong>{user?.isGuest ? 'Local workspace' : `Signed in as ${user?.email || user?.name}`}</strong><p>Data: {state.syncStatus}. {state.pendingCount || 0} changes awaiting sync.</p>{state.syncError && <p>{state.syncError}</p>}{user?.isGuest && <p>Records stay on this device. Sign in to a configured backend for account sync; your local data is not silently assigned to another account.</p>}</div>{state.syncConflicts?.length > 0 && <div className="notice warning">{state.syncConflicts.length} conflicts require review. Export your local data before choosing a resolution in Settings.</div>}<div><h3>Google Calendar</h3><p className="muted">{integration.state === 'connected' && integration.scopes?.includes('calendar.app.created') ? 'Connected. Approved plans use Google Calendar reminders.' : `Connection: ${integration.state || 'unconfigured'}.`}</p><p className="caption">Only an approved date is exported. Your app session and Google access are managed separately.</p><div className="row-actions" style={{ marginTop: '.75rem' }}><Button variant="secondary" disabled={!capabilities.auth || user?.isGuest} loading={busy} onClick={() => run(() => connectGoogle('calendar'))}>Connect Google Calendar</Button>{integration.state === 'connected' && <Button variant="ghost" onClick={() => run(async () => { await disconnectGoogle(); await refreshSession() })}>Disconnect</Button>}</div>{!capabilities.auth && <p className="caption">Unavailable until the backend and Google OAuth are configured. Local planning still works.</p>}</div><div><h3>Reminders</h3><p className="muted">In-app pending check-ins are always available.</p><p className="caption">Closed-app push requires a configured server, device subscription and permission. Delivery has not been verified for this device. Calendar reminders provide another fallback after export.</p></div><div className="row-actions"><Button variant="secondary" onClick={() => run(synchronize)} disabled={user?.isGuest} loading={busy}>Sync now</Button><Link className="button button-secondary" to="/settings"><Download size={16}/>Backup, restore & privacy</Link><Button variant="ghost" onClick={() => run(logout)}>Sign out</Button></div></div></section>
    <DriveImport/><section className="section-card"><h2>Make it your own</h2><p className="muted" style={{ margin: '.5rem 0 1rem' }}>Keep optional areas only when they are useful to you.</p><div className="page-stack">{optional.map(([path, name, description]) => <label key={path} className="row-actions"><input type="checkbox" checked={optionalEnabled.includes(path)} onChange={() => toggleModule(path)}/><span><strong>{name}</strong><span className="caption"> · {description}</span></span></label>)}</div><details style={{ marginTop: '1rem' }}><summary>More tools & historical content</summary><div className="row-actions"><Link className="button button-ghost" to="/wisdom">Saved wisdom</Link><Link className="button button-ghost" to="/decisions">Decision notes</Link><Link className="button button-ghost" to="/wrapped">Year in review</Link><Link className="button button-ghost" to="/analysis-builder">Custom analysis</Link><Link className="button button-ghost" to="/scoring">Optional score settings</Link></div><p className="caption">Existing optional records and archived RPG data remain available in your backup. No points, coins or reward economy are active in the daily experience.</p></details></section>{error && <p className="notice error" role="alert">{error}</p>}
  </div>
}
