export const initialState = {
  finance: { expenses: [], budgets: {}, categories: [], bills: [], savingsGoals: [] },
  timeflow: { entries: [] },
  study: { sessions: [], goals: {}, subjects: [], flashcards: [] },
  habits: { checkpoints: [], dailyLogs: [] },
  health: { imported: {}, manualLogs: [], energyLogs: [], waterLogs: [] },
  journal: { entries: [] },
  wisdom: { entries: [] },
  goals: { entries: [] },
  decisions: { entries: [] },
  crm: { contacts: [] },
  secondBrain: { notes: [] },
  readings: { books: [] },
  meditations: { sessions: [] },
  settings: {
    profile: {
      name: '',
      avatar: '🧠',
      currency: 'INR',
      timezone: 'Asia/Kolkata',
    },
    preferences: {
      dailyStudyGoal: 0,
      monthlyBudget: 0,
      dailyWasteLimit: 2,
      sleepGoal: 8,
      dailyStepGoal: 10000,
      theme: 'dark',
      soundEnabled: false,
      notificationsEnabled: false,
      dailyCheckinReminder: '21:00',
      budgetAlertAt: 80,
      streakRiskWarning: true,
      weeklyReportDay: 'Sunday',
      expenseCategories: [
        'Food',
        'Drinks',
        'Groceries',
        'Transport',
        'Gym Fitness',
        'Study Education',
        'Shopping',
        'Bills Utilities',
        'Health Medical',
        'Entertainment',
        'Subscriptions',
        'Travel',
        'Personal Care',
        'Gifts',
        'Miscellaneous',
      ],
      timeCategories: [
        'Sleep',
        'Morning Routine',
        'Exercise',
        'Study',
        'Deep Work',
        'Meals',
        'Social Media',
        'Entertainment',
        'Travel',
        'Self-Care',
        'Waste Time',
        'Other',
      ],
    },
  },
  aiChat: { messages: [] },
  planning: { drafts: {}, revisions: [], checkins: [], timer: null, reviews: [], exportStatus: {} },
  captures: { items: [], draftText: '', retainRaw: false },
  activities: { entries: [] },
  syncStatus: 'idle',
  lastSynced: null,
  lastRemoteModified: null,
  remoteMetadata: {},
  hydrated: false,
  isFromDrive: false,
}
